In [1]:
import numpy as np

In [30]:
# Tableau d'entiers:

np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [31]:
# Une liste de listes est transformée en un tableau multi-dimensionnel
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [3]:
# Un tableau de longueur 10, rempli d'entiers qui valent 0
np.zeros(10, dtype=int)

array([0., 0., 0.])

In [5]:
# Un tableau de taille 3x5 rempli de nombres à virgule flottante de valeur 1
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
# Un tableau 3x5 rempli de 3,14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [14]:
# Un tableau rempli d'une séquence linéaire
# commençant à 0 et qui se termine à 20, avec un pas de 2
np.arange(0, 20, 2)

array([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

In [ ]:
# Un tableau de 5 valeurs, espacées uniformément entre 0 et 1
np.linspace(0, 1, 5)

In [10]:
# Celle-ci vous la conaissez déjà! Essayez aussi "randint" et "normal"
np.random.random((3, 3))

2

In [11]:
# La matrice identité de taille 3x3 
# (matrice identité : https://fr.wikipedia.org/wiki/Matrice_identit%C3%A9)
np.eye(3)

(10, 20)

## Les propriétés des tableaux

In [34]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)  # Tableau de dimension 1
print("nombre de dimensions de x1: ", x1.ndim)
print("forme de x1: ", x1.shape)
print("taille de x1: ", x1.size)
print("type de x1: ", x1.dtype)

nombre de dimensions de x1:  1
forme de x1:  (6,)
taille de x1:  6
type de x1:  int32


## Indexation et slicing

In [36]:
print(x1)

[5 0 3 3 7 9]


### Accéder à un seul élément


In [37]:
# Pour accéder au premier élément
print(x1[0])

5


In [38]:
# Pour accéder au dernier élément
print(x1[-1])

9


In [39]:
x2 = np.random.randint(10, size=(3, 4))  # Tableau de dimension 2
print(x2[0,1])

5


In [40]:
# On peut aussi modifier les valeurs
x1[1] = "1000"
print(x1)

[   5 1000    3    3    7    9]


In [41]:
# Attention au type
x1[1] = 3.14
print(x1)

[5 3 3 3 7 9]


### Accéder à un seul élément


In [42]:
print(x1[:5])  # Les cinq premiers éléments

print(x1[5:])  # Les éléments à partir de l'index 5

print(x1[::2])  # Un élément sur deux

[5 3 3 3 7]
[9]
[5 3 7]


In [43]:
x1[::-1] # Inversion d'un tableau

array([9, 7, 3, 3, 3, 5])

In [44]:
print(x2)

x2[0,:] # La première ligne

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


array([3, 5, 2, 4])

### Concaténation

In [45]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

Si les tableaux sont de dimension > 1, on peut utiliser soit  vstack  (vertical) ou  hstack.

In [48]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

## Opérations sur les tableaux Numpy

### Les temps d'execution

In [53]:
def calcul_inverse(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
print(calcul_inverse(values))

tableau_large = np.random.randint(1, 100, size=1000000)

[0.25 0.5  0.25 1.   0.5 ]


In [54]:
# Ceci est une facilité des notebooks jupyter pour 
# mesurer le temps d'exécution d'une instruction
%timeit calcul_inverse(tableau_large)

1.59 s ± 7.68 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [55]:
%timeit (1.0/tableau_large)

2.88 ms ± 64.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### Les fonctions universelles

In [57]:
# Opérations mathématiques simples
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # Division avec arrondi

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [59]:
# Appel de fonctions sur les tableaux numpy

x = [-2, -1, 1, 2]
print("La valeur absolue: ", np.abs(x))
print("Exponentielle: ", np.exp(x))
print("Logarithme: ", np.log(np.abs(x)))

La valeur absolue:  [2 1 1 2]
Exponentielle:  [0.13533528 0.36787944 2.71828183 7.3890561 ]
Logarithme:  [0.69314718 0.         0.         0.69314718]


### Opérations booléennes

In [60]:
x = np.random.rand(3,3)
x>0.5

array([[ True, False, False],
       [False, False,  True],
       [ True, False, False]])

In [62]:
# Retourne les index des éléments du tableau qui vérifient la condition
np.where(x > 0.5)

(array([0, 1, 2], dtype=int64), array([0, 2, 0], dtype=int64))

### Aggrégation


In [63]:
L = np.random.random(100)
np.sum(L)

58.94439676125687

In [64]:
%timeit sum(tableau_large)

102 ms ± 210 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [65]:
%timeit np.sum(tableau_large)

312 µs ± 4.83 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [68]:
# aggrégation sur colonne ou ligne (axis = [0, 1])
M = np.random.random((3, 4))
print(M)

print(" La somme de tous les éléments de M: ", M.sum())
print(" La somme des colonnes de M: ", M.sum(axis = 1))

[[0.32669668 0.27681393 0.97519106 0.50477233]
 [0.25881728 0.42730462 0.85460843 0.4546536 ]
 [0.26488285 0.10745098 0.53137959 0.57503366]]
 La somme de tous les éléments de M:  5.557605017996549
 La somme des colonnes de M:  [2.083474   1.99538392 1.47874709]
